### ISSUE TITLE
Adjoint of centered joDFT gives different results for vector or single column matrix

### ISSUE THREAD

**Issue by ziyiyin97** [slimgroup/JOLI.jl#39]
For the same vector being written as a `Vector` or a single column `Matrix`, applying the adjoint of the centered `joDFT` leads to different results.

To be more specific, this only happens when/for
1. the `centered` argument is set to true
2. evaluation of the adjoint

I suspect there is something wrongly set up in the FFTW plans but I don't have much experience on that. Any suggestion for me? Thanks!!

MFE is below

```julia
julia> using JOLI

julia> F = joDFT(5; centered=true)
(joLinearFunction{Float64, ComplexF64}, (5, 5), "joDFT_pc")

julia> x = randn(ComplexF64, 5)
5-element Vector{ComplexF64}:
  0.8513875577378983 + 0.16922588539691524im
 -0.6962575216015822 - 0.6144307093988183im
  0.8680312885735334 - 0.8018606520631204im
 -0.1585656190063532 + 1.1665605997881066im
  0.5107059917201883 + 0.5962312153644129im

julia> F' * x
5-element Vector{Float64}:
  0.6150536170020412
 -1.0924941767214393
  0.5991649539548485
  1.1722550665007208
  0.6469975071109862

julia> F' * reshape(x,:,1)
5×1 Matrix{Float64}:
  0.6150536170020413
 -0.7371427840988428
 -0.5825072292749941
 -0.5141049528009984
  0.8641378461802558
```

**Comment by mloubout** [comment]
So I'm not gonna give the answer because this is things you need to learn to do. And it's nothing fancy, it literally takes 5min to figure out and fix it.

>I suspect there is something wrongly set up in the FFTW plans but I don't have much experience on that. 

This is a guess out of nowhere that doesn't actually help the person looking at the issue because you are pointing them towards a random path that turn out to be the wrong one by just. guessing.

So let's make it simple. What's the difference between `centered` and `not centered` in the adjoint mode and what's the difference between Vector and Matrix. THis literally boils down to comparing two lines of codes.
